# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM golang:1.26.5-alpine AS build
ARG TARGETOS
ARG TARGETARCH
RUN apk --no-cache add tzdata

WORKDIR /src/

COPY go.mod go.sum /src/

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY internal /src/internal
COPY .gen /src/.gen

ARG APPNAME=main
COPY cmd/${APPNAME} /src/cmd/${APPNAME}
RUN --mount=type=cache,target=/root/.cache/go-build \
    cd /src/cmd/${APPNAME} && CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /src/main .

FROM scratch AS final

COPY --from=build /src/main /

WORKDIR /
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=America/Vancouver
ENV GIN_MODE=release
USER nobody

ENTRYPOINT [ "/main" ]

FROM postgres:16-alpine AS cron
COPY --from=build /src/main /usr/local/bin/auto_backup
COPY ./cron.d/root /etc/cron/

FROM final AS final-with-server-assets
COPY ./server_assets /server_assets/
COPY ./db_migrations /db_migrations/

ENTRYPOINT [ "/main" ]