name: Build container image (generic)
# Generic workflow to build and publish Docker images for arm64 and x64 platforms

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to publish the built image'
        required: false
        type: boolean
        default: true
      service-name:
        description: 'Service name'
        required: true
        type: string
      service-dockerfile:
        description: 'Service Dockerfile'
        required: true
        type: string
      service-context:
        description: 'Service context'
        required: true
        type: string
      service-target:
        description: 'Service target'
        required: true
        type: string
      service-build-args:
        description: 'Service build args'
        required: true
        type: string
      container-registry-host:
        description: 'Container registry host'
        default: 'ghcr.io'
        type: string
      container-registry-owner:
        description: 'Container registry owner'
        default: 'tomerh2001'
        type: string
      image-name-prefix:
        description: 'Image name prefix'
        default: 'ghcr.io/tomerh2001/maple-culvert-tracker'
        type: string

jobs:
  publish-pre-release:
    name: "Publish pre-release: ${{ inputs.service-name }} - ${{ matrix.platform.manifest-name }}"
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - name: linux/amd64
            runner: ubuntu-latest
            manifest-name: x64
          - name: linux/arm64
            runner: ubuntu-24.04-arm
            manifest-name: arm64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ inputs.container-registry-host }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: 'false'
        with:
          tags: ${{ inputs.image-name-prefix }}/${{ inputs.service-name }}
          platforms: ${{ matrix.platform.name }}
          outputs: ${{ inputs.publish && 'type=image,push-by-digest=true,push=true' || 'type=image,push-by-digest=true,push=false' }}
          file: ${{ inputs.service-dockerfile }}
          context: ${{ inputs.service-context }}
          target: ${{ inputs.service-target }}
          build-args: ${{ inputs.service-build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Write image sha to output
        if: ${{ inputs.publish }}
        id: write-image-sha
        run: |
          echo "${{ steps.build.outputs.digest }}"
          echo "${{ matrix.platform.manifest-name }}_sha=${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"
    outputs:
      x64_sha: ${{ steps.write-image-sha.outputs.x64_sha }}
      arm64_sha: ${{ steps.write-image-sha.outputs.arm64_sha }}
  publish:
    if: ${{ inputs.publish }}
    name: Publish build - ${{ inputs.service-name }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs:
      - publish-pre-release
    steps:
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ inputs.container-registry-host }}
          username: ${{ inputs.container-registry-owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker buildx imagetools create -t "${{ inputs.image-name-prefix }}/${{ inputs.service-name }}:HEAD" \
            -t "${{ inputs.image-name-prefix }}/${{ inputs.service-name }}:${{ github.sha }}" \
            "${{ inputs.image-name-prefix }}/${{ inputs.service-name }}@${{ needs.publish-pre-release.outputs.x64_sha }}" \
            "${{ inputs.image-name-prefix }}/${{ inputs.service-name }}@${{ needs.publish-pre-release.outputs.arm64_sha }}"